In [1]:
#8.	Create:
#- A scalar using np.array(5)
#- A 1D array with values 1 to 5
#- A 2D array (2x3) with values from 10 to 60 in steps of 10

import numpy as np

# 1. Scalar
scalar = np.array(5)
print("Scalar:")
print(scalar)
print("Shape:", scalar.shape)
print()

# 2. 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)
print("Shape:", array_1d.shape)
print()

# 3. 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])
print("2D Array:")
print(array_2d)
print("Shape:", array_2d.shape)

Scalar:
5
Shape: ()

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[10 20 30]
 [40 50 60]]
Shape: (2, 3)


In [2]:
# 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
import random
import numpy as np

# Generate a 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))

print("4x4 Random Integer Array:")
print(random_array)

4x4 Random Integer Array:
[[ 85  19 100  80]
 [ 69  47   4  40]
 [ 76  43  60  77]
 [  7  34 100  52]]


In [3]:
# 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.
import numpy as np
import pandas as pd

# Create a 2D NumPy array of shape (3x3)
array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Convert the NumPy array into a Pandas DataFrame
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])

print(df)


   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
